language: python

python:
  - 2.7
  - 3.4

branches:
  only:
    - master

cache:
  directories:
    - node_modules

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - pip install .
  - pip install -e .[test]

before_script:
  - npm install

script:
  - py.test damvitool
  - npm test
